FROM nginx:alpine
COPY . /usr/share/nginx/html
# Staging: swap in the staging-specific landing page
COPY index-staging.html /usr/share/nginx/html/index.html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080
